CVE-2024-21538: Update cross-spawn transitives to latest
shipt/osmosis pull request #180
Opened 2024-11-22 17:33 UTC by adkenyon

Closes CVE-2024-21538

https://app.clickup.com/t/86b2yndwu

2024-11-22 18:14 UTC, calebmackdavenport approved these changes

2024-11-22 18:38 UTC, chaceburnette requested changes
@adkenyon looks like dependabot is on it, and goes to 7.0.6...any reason not to just merge that one?
https://github.com/shipt/osmosis/pull/179

2024-11-22 18:51 UTC, adkenyon commented
@chaceburnette I didn't realize 7.0.6 was available. I can update to that version. 

I vaguely recall that we wanted to shy away from Dependabot PRs as they don't explicitly tie to ClickUp tasks therefore aren't as easily traceable in the event of an audit.

@jeacovy What are your thoughts on this?

2024-12-10 18:28 UTC, adkenyon commented
@chaceburnette I'll go ahead and close this. I _do_ need the Dependabot PR approved and merged soon (<10 days until we're out of compliance)

2024-12-10 18:29 UTC, closed without merging